<a href="https://colab.research.google.com/github/Enkhzol/diveintocode-ml/blob/master/diver_class_assignment14_CreditInformationLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**[Problem 1] Confirmation of competition contents**

Read the overview page of the competition and check the following points about "Home Credit Default Risk".

* What to learn and what to predict?
-- Learn the data of application_train and predict the probability of repayment by financing.

* What kind of file to create and submit to Kaggle?
-- ID and prediction probability in two columns.
* What kind of index value will be used to evaluate the submissions?
-- ROC curve (calculate true positive rate (= TPF) and false positive rate (= FPF), plot on a plane with TPF on the vertical axis and FPF on the horizontal axis, and connect them with a line to create an ROC curve. The area at the bottom of the graph is called AUC (Area Under the Curve). It does not depend on the existence of other lines. AUC takes a value from 0 to 1, and the closer the value is to 1, the better the discrimination ability. Indicates that is high.)

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import kurtosis
from scipy.stats import skew
import pylab as pl

application_train = pd.read_csv('sample_data/application_train_few.csv')
application_test = pd.read_csv('sample_data/application_test_few.csv')

application_train = pd.DataFrame(application_train)
application_test = pd.DataFrame(application_test)

print(application_train.shape)
print(application_test.shape)

(3864, 122)
(11132, 121)

**[Problem 2] Learning and verification**
Create and execute a series of steps from easy analysis, preprocessing, learning, and verification of data.


For verification, please use the evaluation metrics used in this competition. The method used for learning is not specified

In [11]:
application_train.info()
print("------------------")
application_test.info()
print("==================")
application_train.describe()
print("------------------")
application_test.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3864 entries, 0 to 3863
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(85), int64(21), object(16)
memory usage: 3.6+ MB
------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11132 entries, 0 to 11131
Columns: 121 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(40), object(16)
memory usage: 10.3+ MB
==================
------------------

          SK_ID_CURR  ...  AMT_REQ_CREDIT_BUREAU_YEAR
count   11132.000000  ...                 9770.000000
mean   140382.610402  ...                    1.953019
std     23590.260518  ...                    1.822658
min    100001.000000  ...                    0.000000
25%    119530.750000  ...                    0.000000
50%    140702.500000  ...                    2.000000
75%    161074.750000  ...                    3.000000
max    180768.000000  ...                   13.000000

[8 rows x 105 columns]

In [13]:
application_train.isnull().sum()
print("------------------")
application_test.isnull().sum()

------------------

SK_ID_CURR                       0
NAME_CONTRACT_TYPE               0
CODE_GENDER                      0
FLAG_OWN_CAR                     0
FLAG_OWN_REALTY                  0
                              ...
AMT_REQ_CREDIT_BUREAU_DAY     1362
AMT_REQ_CREDIT_BUREAU_WEEK    1362
AMT_REQ_CREDIT_BUREAU_MON     1362
AMT_REQ_CREDIT_BUREAU_QRT     1362
AMT_REQ_CREDIT_BUREAU_YEAR    1362
Length: 121, dtype: int64

In [34]:
from sklearn.model_selection import train_test_split

app_train1 = application_train.loc[:, ['SK_ID_CURR', 'AMT_INCOME_TOTAL','DAYS_BIRTH', 'TARGET']]
app_test1 = application_test.loc[:, ['SK_ID_CURR', 'AMT_INCOME_TOTAL','DAYS_BIRTH']]

#learning data and verification data
X_train, X_test, Y_train, Y_test = train_test_split(np.array(app_train1.iloc[:, [0, 1, 2]])
                                                         , np.array(app_train1.iloc[:, [3]]), random_state = 0)

print(X_train.shape)

(2898, 3)

In [35]:
Y_train = Y_train.reshape(-1)
Y_test = Y_test.reshape(-1)

In [36]:
# Random forest

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train, Y_train)
Y_pred= clf.predict_proba(X_test)[:, 1]

from sklearn.metrics import roc_auc_score
print('roc score:', roc_auc_score(Y_test, Y_pred))

roc score: 0.568000843748352

**[Problem 3] Estimation on test data**

Perform the estimation on the test data (application_test.csv ) and submit it to Kaggle.


It does not matter if the accuracy is low, as long as the submission is done correctly.

DONE.

**[Problem 4] Feature engineering**

To improve accuracy, perform Feature Engineering from the following perspectives.


Which feature to use?
How to preprocess?

Summarize what you did and how the evaluation metrics for the validation data turned out. Please conduct at least 1 patterns of training and validation.


If the accuracy is high, please make an estimate for the test data and submit it to Kaggle.

In [37]:
# added AMT_CREDIT 
# roc score: 0.568000843748352 => 0.5964773506301746
app_train2 = application_train.loc[:, ['SK_ID_CURR', 'AMT_INCOME_TOTAL','AMT_CREDIT','DAYS_BIRTH', 'TARGET']]
app_test2 = application_test.loc[:, ['SK_ID_CURR', 'AMT_INCOME_TOTAL','AMT_CREDIT','DAYS_BIRTH']]

#learning data and verification data
X_train2, X_test2, Y_train2, Y_test2 = train_test_split(np.array(app_train2.iloc[:, [0, 1, 2, 3]])
                                                         , np.array(app_train2.iloc[:, [4]]), random_state = 0)

Y_train2 = Y_train.reshape(-1)
Y_test2 = Y_test.reshape(-1)

clf2 = RandomForestClassifier(max_depth=2, random_state=0)
clf2.fit(X_train2, Y_train2)
Y_pred2= clf2.predict_proba(X_test2)[:, 1]

print('roc score:', roc_auc_score(Y_test2, Y_pred2))

roc score: 0.5964773506301746